Fix missing 'DEFAULT_RESOLUTION' from ps6000a.
When we run the README example code, in "scopes = find_all_units()" an error pops up: "AttributeError: 'Ps6000alib' object has no attribute 'DEFAULT_RESOLUTION'.
This change fix that bug.